### ISSUE TITLE
add Facebook Open Graph description tag explaining 

### ISSUE THREAD

**Issue by ericfont** [ro31337/libretaxi-www#10]
If I share the url to facebook, the following what people are going to see on their newsfeed:

![screenshot 112](https://cloud.githubusercontent.com/assets/6502474/22493756/078d94b0-e800-11e6-8b97-3ed01d5e73f8.png)

Notice that there is a bunch of white space without any description.  This is because according to https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Flibretaxi.org there is no og:description tag.

 When I shared the link to facebook, I felt that I needed to explain a little about it, primarily how it is different from Uber/Lyft and why one would want to use it instead.  But I think best if that type of info be in the link's description.  Probably could just reuse this text you already have on your website: "LibreTaxi makes taxi affordable by getting rid of the third party between passengers and drivers. Negotiate the price before the ride is confirmed, pay cash upon arrival. 1-minute hiring for all drivers."

**Comment by ericfont** [comment]
I see you added the help wanted tag.  I could easily provide a PR for this.  According to facebook's open graph debugger https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Flibretaxi.org%2F there are some other warnings:

- Inferred Property	The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
-Inferred Property	The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
-Inferred Property	The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
-Share App ID Missing	The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.

But note that those first three are already correctly inferred, so only reason you would want to change that is if you want the facebook link to have a different title, or if there were multiple images on the index.html and you wanted to make sure to tell facebook to use a specific image.

**Comment by ericfont** [comment]
for now I will set the og:image to 2-en.jpg for every language except russian, to make sure that facebook uses the image with the google map thumbnail (which I think better communicates the functionality instead of the other text-only image).

**Comment by ericfont** [comment]
I made a PR https://github.com/ro31337/libretaxi-www/pull/13 for desription.  I didn't bother adding an op:image, because I realize that might be better to have a facebook-specific thumbnail (since the current one cuts off the top and bottom of the image).

**Comment by ro31337** [comment]
Thanks, looks great. Will merge and deploy in few hours.

**Comment by ro31337** [comment]
Closing this issue - fixed by Eric. Thanks again for your contribution!
