### ISSUE TITLE
Add Persian website translation

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi-www#17]
There was Persian translation added in this PR: https://github.com/ro31337/libretaxi/pull/435 for application.

It was not yet merged to master at the moment of writing, and it's on the way (it's our priority). But what we need now the website http://libretaxi.org translated to Persian. **It's important**, because Telegram is wide-spread in Persian speaking countries.

You just need to translate `index.html` in this repository. It's pure HTML. You can skip adding links to every page, I can take care of them.

Thank you! <3 <3 <3

**Comment by danialbehzadi** [comment]
This PR: https://github.com/ro31337/libretaxi-www/pull/21

**Comment by ro31337** [comment]
@danialbehzadi thanks for your contribution. Language will be added to the app in a day or two.
