### ISSUE TITLE
Add Spanish website translation

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi-www#2]
There was Portuguese translation added in this PR: https://github.com/ro31337/libretaxi-www/pull/1 for the website: http://libretaxi.org

It was merged to master. Application itself supports Spanish, thanks to @asccigcc

Now we should translate the website into Spanish, the same way it was done for Portuguese. So we need to translate only `index.html` in this repository.

For translator: feel free to create PR right to `master`, feel free to skip updating links on other pages if you don't have time (I will update them). You basically need to translate and commit 1 page only.

**Comment by asccigcc** [comment]
Awesome, I'm on my way.

**Comment by ro31337** [comment]
Closing as done in https://github.com/ro31337/libretaxi-www/pull/4

@asccigcc Nico did it ;)

**Comment by asccigcc** [comment]
Awesome!
