### ISSUE TITLE
Add Ukrainian translation

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi-www#39]
Bot was translated to Tamil language here: https://github.com/ro31337/libretaxi/issues/559 and we need to translate the website (http://libretaxi.org/) into Ukrainian the same way it was done for other languages: by translating index.html in this repository.

For translator: feel free to create PR right to master, feel free to skip updating links on other pages if you don't have time (I will update them). You just need to translate and commit 1 page only.

**Comment by ivanzusko** [comment]
@ro31337 , [**done**](https://github.com/ro31337/libretaxi-www/pull/40)

**Comment by ro31337** [comment]
Thanks for contribution, translation has been added!
