### ISSUE TITLE
Feature request: Driver count near me

### ISSUE THREAD

**Issue by mattiasaxell** [ro31337/libretaxi-www#48]
Feature request: A potential user (ping @peterk ) would like to see a "Driver Count Near Me"-feature.

From user flow perspective I can imagine it would be nice to be able to see amount of checked-in drivers close by at two places using LibreTaxi bot:

1. When user is considering to search for a ride
2. When continously having search activated

Just ideas I came up with on the fly.

**Comment by ro31337** [comment]
Good place for this issue is here: https://github.com/ro31337/libretaxi/issues
